### ISSUE TITLE
Avram: support keys deprecated-fields and deprecated-subfields

### ISSUE THREAD

**Issue by cKlee** [gbv/format.gbv.de#25]
Deprecated (sub)fields should be made explicit. Then a deprecated-warning can be created. If the description-key would be applicable in a (sub)field-definitions and code-definition then this warning could be more verbose.

```yaml
fields:
  [...]
    deprecated-subfields:
      a:
        code: a
        label: xxx
        description: wird mit Umstieg auf RDA nicht mehr verwendet
    subfields:
      b:
        deprecated-codes:
            sm:
              label: sekundäre Mikroform
              description: wird mit dem Umstieg auf RDA nicht mehr verwendet
deprecated-fields:
  011B:
    tag: 011B
    pica3: 1109
    label: Erscheinungsjahr der Sekundärausgabe
    description: wird mit Umstieg auf RDA nicht mehr verwendet
```

The keyword description should also be applicable in all definitions.
