### ISSUE TITLE
Avram: support key rule

### ISSUE THREAD

**Issue by cKlee** [gbv/format.gbv.de#26]
The key `rule` could contain a (set of) MARCspec **subspec(s)** to make inner record logic explicit. Some fields and subfields have dependencies and this could be checked with a MARCspec.

The key `rule` could be used in `field definition`,   `subfield definition`,  `field type definition`,  `code definition`.  

It is not reasonable to use a full MARCspec as the value of the key `rule`, because the current (sub)field occurrence is unknown. Thus an application must create a full MARCspec from current field tag, the current (sub)field occurrence or the current character position for fixed fields.

E.g. Subfield q is only valid if subfield a or z is given

```yaml
fields:
  '020':
    tag: '020'
    label: International Standard Book Number
    subfields:
      q:
        rule: '{$a|$z}'
```

Field 020 is repeatable. For every field occurrence the corresponding MARCspec will look like

```
020[0]$q[0]{$a|$z} // same as 020[0]$q[0]{020[0]$a|020[0]$z}
020[1]$q[0]{$a|$z} // same as 020[1]$q[0]{020[1]$a|020[1]$z}
...
```

E.g. The rule in the field types can be used to decide if field type is applicable. The rule in the code definition validates validates the code usage by checking the content of another field:

```yaml
fields:
  '008':
    tag: '008'
    types:
      Books:
        rule: '{LDR/6=\a}{LDR/7=\a|LDR/7=\c|LDR/7=\d|LDR/7=\m}'
        positions:
          "18-21":
            codes:
              b:
                label: Maps
                rule: '{300~\map}'
```

Field 008 is not repeatable. Following MARCspec must be created:

```
008{LDR/6=\a}{LDR/7=\a|LDR/7=\c|LDR/7=\d|LDR/7=\m}
008/18-21{300~\map}
```
